name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install protobuf-compiler -y
    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install required cargo
      run: cargo install clippy-sarif sarif-fmt
    - name: Run rust-clippy
      run:
         cargo clippy
         --all-features
         --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      continue-on-error: true

    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
         sarif_file: rust-clippy-results.sarif
         wait-for-processing: true