name: Rust

on:
  push:
    branches: ["main", "staging"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y build-essential
          sudo apt install --assume-yes git clang curl libssl-dev protobuf-compiler
          sudo apt-get install protobuf-compiler -y
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install  wasm
        run: |
          rustup target add wasm32-unknown-unknown --toolchain nightly
          rustup target add wasm32-unknown-unknown
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release --verbose
        continue-on-error: false
